-- Supabase/PostgreSQL schema for the portfolio application.
-- Run this once in Supabase > SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" varchar(64) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role text not null default 'user' check (role in ('user', 'admin')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.portfolio_settings (
  id bigint generated by default as identity primary key,
  "userId" bigint not null unique references public.users(id) on delete cascade,
  "portfolioName" varchar(255) not null default 'Meu Portfólio',
  tagline varchar(500) default '',
  "aboutTitle" varchar(255) default 'Sobre',
  "aboutText" text default '',
  "shortBio" text default '',
  "profileImageUrl" text default '',
  "profileImageKey" text default '',
  whatsapp varchar(30) default '',
  "emailPublic" varchar(320) default '',
  location varchar(255) default '',
  "socialLinks" jsonb not null default '[]'::jsonb,
  "contactIntro" text default '',
  "uxVoice" varchar(64) default 'direto',
  "themeConfig" jsonb not null default '{}'::jsonb,
  "faviconUrl" text default '',
  "faviconKey" text default '',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  "userId" bigint not null references public.users(id) on delete cascade,
  name varchar(255) not null,
  slug varchar(255) not null,
  description text default '',
  "displayOrder" integer not null default 0,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  "userId" bigint not null references public.users(id) on delete cascade,
  "categoryId" bigint references public.categories(id) on delete set null,
  title varchar(255) not null,
  slug varchar(255) not null,
  "shortDescription" text default '',
  "coverImageUrl" text default '',
  "coverImageKey" text default '',
  "coverImageAlt" varchar(500) default '',
  year varchar(10) default '',
  status text not null default 'draft' check (status in ('draft', 'published')),
  featured boolean not null default false,
  "displayOrder" integer not null default 0,
  "metaDescription" text default '',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.project_blocks (
  id bigint generated by default as identity primary key,
  "projectId" bigint not null references public.projects(id) on delete cascade,
  "userId" bigint not null references public.users(id) on delete cascade,
  type text not null check (type in ('text', 'image', 'youtube', 'audio')),
  content text default '',
  "mediaUrl" text default '',
  "mediaKey" text default '',
  "altText" varchar(500) default '',
  caption text default '',
  transcript text default '',
  "displayOrder" integer not null default 0,
  "createdAt" timestamptz not null default now()
);

create index if not exists categories_user_order_idx
  on public.categories ("userId", "displayOrder");

create index if not exists projects_user_order_idx
  on public.projects ("userId", "displayOrder");

create index if not exists projects_user_status_idx
  on public.projects ("userId", status);

create index if not exists projects_user_slug_idx
  on public.projects ("userId", slug);

create index if not exists project_blocks_project_order_idx
  on public.project_blocks ("projectId", "displayOrder");

-- Keep updatedAt current on edits.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists portfolio_settings_set_updated_at on public.portfolio_settings;
create trigger portfolio_settings_set_updated_at
before update on public.portfolio_settings
for each row execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

-- Supabase Storage bucket used by the portfolio uploads.
insert into storage.buckets (id, name, public)
values ('portfolio-media', 'portfolio-media', true)
on conflict (id) do update set public = excluded.public;

-- The server uses the service-role key, so these policies are not required for
-- server uploads. The bucket is public so portfolio images can be displayed
-- directly from their generated public URLs.


-- A autenticação de e-mail/senha é feita pelo Supabase Auth (auth.users).
-- O servidor sincroniza automaticamente o usuário autenticado para public.users.
-- Para tornar a sua conta administradora, defina OWNER_EMAIL na Vercel com o
-- mesmo e-mail da conta. No próximo login, a coluna role será atualizada para admin.

-- ---------------------------------------------------------------------------
-- Data API permissions (required on new Supabase projects created with the
-- opt-in Data API exposure model).
--
-- This app never queries these tables directly from the browser. All database
-- access goes through the Vercel server using a Supabase Secret/service-role
-- key, so only service_role needs table privileges. RLS remains enabled as a
-- defense-in-depth boundary for any accidental client-side access.
-- ---------------------------------------------------------------------------

grant usage on schema public to service_role;

grant select, insert, update, delete on table
  public.users,
  public.portfolio_settings,
  public.categories,
  public.projects,
  public.project_blocks
to service_role;

grant usage, select on all sequences in schema public to service_role;

revoke all on table
  public.users,
  public.portfolio_settings,
  public.categories,
  public.projects,
  public.project_blocks
from anon, authenticated;

alter table public.users enable row level security;
alter table public.portfolio_settings enable row level security;
alter table public.categories enable row level security;
alter table public.projects enable row level security;
alter table public.project_blocks enable row level security;

-- Keep future tables/sequences server-only by default when this schema is
-- extended later.
alter default privileges for role postgres in schema public
  grant select, insert, update, delete on tables to service_role;
alter default privileges for role postgres in schema public
  grant usage, select on sequences to service_role;
