import React, { useMemo, useState } from 'react';
import { usePortfolio } from '../../context/PortfolioContext';
import { PRESET_THEMES, normalizeThemeConfig, calculateContrastRatio, getWCAGStatus } from '../../lib/theme';
import { ThemeConfig } from '../../types';
import { Palette, Save, Eye, Accessibility, Type, Layout, Navigation, MousePointer2 } from 'lucide-react';

const Field = ({label, children, hint}:{label:string;children:React.ReactNode;hint?:string}) => <label className="block space-y-1.5"><span className="text-xs font-bold">{label}</span>{children}{hint&&<span className="block text-[11px]" style={{color:'var(--theme-text-secondary)'}}>{hint}</span>}</label>;
const Text = ({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder?:string}) => <input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="w-full px-3 py-2.5 rounded-xl border text-sm bg-transparent" style={{borderColor:'var(--theme-border)',color:'var(--theme-text-primary)'}}/>;
const Select = ({value,onChange,children}:{value:string;onChange:(v:string)=>void;children:React.ReactNode}) => <select value={value} onChange={e=>onChange(e.target.value)} className="w-full px-3 py-2.5 rounded-xl border text-sm bg-transparent" style={{borderColor:'var(--theme-border)',color:'var(--theme-text-primary)',backgroundColor:'var(--theme-surface)'}}>{children}</select>;
const Color = ({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) => <Field label={label}><div className="flex gap-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-12 rounded-lg border cursor-pointer"/><Text value={value} onChange={onChange}/></div></Field>;

export const AdminAppearance: React.FC = () => {
  const { settings, updateSettings, addToast } = usePortfolio();
  const [themeForm, setThemeForm] = useState<ThemeConfig>(() => normalizeThemeConfig(settings.theme_config));
  const set = <K extends keyof ThemeConfig>(key:K, value:ThemeConfig[K]) => setThemeForm(prev=>({...prev,[key]:value}));
  const colors = themeForm.colors;
  const updateColors = (key:keyof ThemeConfig['colors'], value:string) => set('colors',{...colors,[key]:value});
  const updateNested = <K extends keyof ThemeConfig>(key:K, value:Partial<ThemeConfig[K]>) => set(key,{...(themeForm[key] as object),...value} as ThemeConfig[K]);
  const textBg = useMemo(()=>getWCAGStatus(calculateContrastRatio(colors.textPrimary,colors.bg)),[colors]);
  const textSurface = useMemo(()=>getWCAGStatus(calculateContrastRatio(colors.textPrimary,colors.surface)),[colors]);
  const save = async(e:React.FormEvent)=>{e.preventDefault();await updateSettings({theme_config:themeForm});addToast('success','Identidade visual salva.');};
  const preview = () => { document.documentElement.style.setProperty('--theme-preview','1'); window.scrollTo({top:0,behavior:'smooth'}); };
  return <form onSubmit={save} className="space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h2 className="text-xl font-bold flex items-center gap-2"><Palette className="w-5 h-5" style={{color:'var(--theme-primary)'}}/>Editor visual completo</h2><p className="text-sm mt-1" style={{color:'var(--theme-text-secondary)'}}>Tudo que estiver aqui pode ser alterado sem editar os componentes públicos.</p></div><div className="flex gap-2"><button type="button" onClick={preview} className="theme-button px-4 py-2.5 border text-sm font-bold flex gap-2 items-center" style={{borderColor:'var(--theme-border)'}}><Eye className="w-4 h-4"/>Pré-visualizar</button><button type="submit" className="theme-button px-5 py-2.5 text-sm font-bold text-white flex gap-2 items-center" style={{backgroundColor:'var(--theme-primary)'}}><Save className="w-4 h-4"/>Salvar tudo</button></div></div>
    <section className="theme-card p-5 space-y-4"><h3 className="font-bold flex items-center gap-2"><Palette className="w-4 h-4"/>Presets</h3><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-3">{PRESET_THEMES.map(p=><button key={p.name} type="button" onClick={()=>setThemeForm(normalizeThemeConfig(p.config))} className="p-4 rounded-xl border text-left hover:scale-[1.01]" style={{backgroundColor:p.config.colors.surface,borderColor:'var(--theme-border)'}}><div className="flex gap-1.5 mb-3"><i className="w-4 h-4 rounded-full" style={{background:p.config.colors.primary}}/><i className="w-4 h-4 rounded-full" style={{background:p.config.colors.accent}}/><i className="w-4 h-4 rounded-full" style={{background:p.config.colors.textPrimary}}/></div><strong className="text-xs" style={{color:p.config.colors.textPrimary}}>{p.name}</strong><p className="text-[11px] mt-1" style={{color:p.config.colors.textSecondary}}>{p.description}</p></button>)}</div></section>
    <section className="theme-card p-5 space-y-5"><h3 className="font-bold flex items-center gap-2"><Palette className="w-4 h-4"/>Cores</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{Object.entries(colors).map(([key,val])=><Color key={key} label={{bg:'Fundo',surface:'Superfície',textPrimary:'Texto principal',textSecondary:'Texto secundário',primary:'Primária',secondary:'Secundária',accent:'Acento',border:'Bordas',focus:'Foco',success:'Sucesso',warning:'Aviso',error:'Erro'}[key]||key} value={val} onChange={v=>updateColors(key as keyof ThemeConfig['colors'],v)}/>)}</div></section>
    <section className="theme-card p-5 space-y-5"><h3 className="font-bold flex items-center gap-2"><Type className="w-4 h-4"/>Tipografia</h3><div className="grid md:grid-cols-2 gap-4"><Field label="Fonte dos títulos" hint="Use uma família disponível no navegador ou uma fonte carregada pelo projeto."><Text value={themeForm.typography.fontHeading} onChange={v=>updateNested('typography',{fontHeading:v})}/></Field><Field label="Fonte do corpo"><Text value={themeForm.typography.fontBody} onChange={v=>updateNested('typography',{fontBody:v})}/></Field><Field label="Tamanho base"><Select value={themeForm.typography.baseSize} onChange={v=>updateNested('typography',{baseSize:v})}><option>14px</option><option>15px</option><option>16px</option><option>17px</option><option>18px</option><option>20px</option></Select></Field><Field label="Escala tipográfica"><Text value={String(themeForm.typography.scaleRatio)} onChange={v=>updateNested('typography',{scaleRatio:Number(v)||1.25})}/></Field></div></section>
    <section className="theme-card p-5 space-y-5"><h3 className="font-bold flex items-center gap-2"><Layout className="w-4 h-4"/>Layout e componentes</h3><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Largura máxima"><Select value={themeForm.layout.maxContainerWidth} onChange={v=>updateNested('layout',{maxContainerWidth:v})}><option>960px</option><option>1100px</option><option>1200px</option><option>1320px</option><option>1440px</option><option>1600px</option></Select></Field><Field label="Espaçamento da grade"><Select value={themeForm.layout.gridGap} onChange={v=>updateNested('layout',{gridGap:v})}><option>12px</option><option>16px</option><option>20px</option><option>24px</option><option>32px</option><option>40px</option></Select></Field><Field label="Colunas de projetos"><Select value={themeForm.layout.cardColumns} onChange={v=>updateNested('layout',{cardColumns:v as '1'|'2'|'3'})}><option value="1">1</option><option value="2">2</option><option value="3">3</option></Select></Field><Field label="Arredondamento"><Select value={themeForm.shape.borderRadius} onChange={v=>updateNested('shape',{borderRadius:v})}><option>0px</option><option>4px</option><option>8px</option><option>12px</option><option>20px</option><option>28px</option></Select></Field><Field label="Bordas"><Select value={themeForm.shape.borderWidth} onChange={v=>updateNested('shape',{borderWidth:v})}><option>0px</option><option>1px</option><option>2px</option><option>3px</option></Select></Field><Field label="Sombra"><Select value={themeForm.shape.shadowStyle} onChange={v=>updateNested('shape',{shadowStyle:v as ThemeConfig['shape']['shadowStyle']})}><option value="none">Nenhuma</option><option value="soft">Suave</option><option value="sharp">Marcada</option><option value="deep">Profunda</option></Select></Field><Field label="Estilo de botões"><Select value={themeForm.components.buttonStyle} onChange={v=>updateNested('components',{buttonStyle:v as ThemeConfig['components']['buttonStyle']})}><option value="solid">Sólido</option><option value="outline">Contorno</option><option value="soft">Suave</option></Select></Field><Field label="Estilo dos cards"><Select value={themeForm.components.cardStyle} onChange={v=>updateNested('components',{cardStyle:v as ThemeConfig['components']['cardStyle']})}><option value="flat">Plano</option><option value="bordered">Com borda</option><option value="elevated">Elevado</option></Select></Field><label className="flex items-center gap-3 text-sm font-semibold pt-7"><input type="checkbox" checked={themeForm.components.hoverLift} onChange={e=>updateNested('components',{hoverLift:e.target.checked})}/> Elevar elementos no hover</label></div></section>
    <section className="theme-card p-5 space-y-5"><h3 className="font-bold flex items-center gap-2"><Navigation className="w-4 h-4"/>Marca e navegação</h3><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Logo"><Select value={themeForm.brand.logoMode} onChange={v=>updateNested('brand',{logoMode:v as ThemeConfig['brand']['logoMode']})}><option value="initial">Inicial</option><option value="name">Nome</option><option value="none">Sem símbolo</option></Select></Field><Field label="Cabeçalho"><Select value={themeForm.brand.headerStyle} onChange={v=>updateNested('brand',{headerStyle:v as ThemeConfig['brand']['headerStyle']})}><option value="solid">Sólido</option><option value="glass">Vidro</option><option value="transparent">Transparente</option></Select></Field><Field label="Espaçamento do cabeçalho"><Select value={themeForm.brand.headerPadding} onChange={v=>updateNested('brand',{headerPadding:v as ThemeConfig['brand']['headerPadding']})}><option value="compact">Compacto</option><option value="normal">Normal</option><option value="large">Grande</option></Select></Field><Field label="Texto: Projetos"><Text value={themeForm.navigation.projectsLabel} onChange={v=>updateNested('navigation',{projectsLabel:v})}/></Field><Field label="Texto: Sobre"><Text value={themeForm.navigation.aboutLabel} onChange={v=>updateNested('navigation',{aboutLabel:v})}/></Field><Field label="Texto: Contato"><Text value={themeForm.navigation.contactLabel} onChange={v=>updateNested('navigation',{contactLabel:v})}/></Field><Field label="Texto: Admin"><Text value={themeForm.navigation.adminLabel} onChange={v=>updateNested('navigation',{adminLabel:v})}/></Field><Field label="Texto: Admin logado"><Text value={themeForm.navigation.authenticatedAdminLabel} onChange={v=>updateNested('navigation',{authenticatedAdminLabel:v})}/></Field><label className="flex items-center gap-3 text-sm font-semibold pt-7"><input type="checkbox" checked={themeForm.navigation.showAdminLink} onChange={e=>updateNested('navigation',{showAdminLink:e.target.checked})}/> Mostrar acesso ao Admin</label><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={themeForm.brand.showTagline} onChange={e=>updateNested('brand',{showTagline:e.target.checked})}/> Mostrar tagline</label></div></section>
    <section className="theme-card p-5 space-y-5"><h3 className="font-bold flex items-center gap-2"><Accessibility className="w-4 h-4"/>Acessibilidade</h3><div className="grid md:grid-cols-3 gap-4"><Field label="Tamanho mínimo de texto"><Select value={themeForm.accessibility.minimumTextSize} onChange={v=>updateNested('accessibility',{minimumTextSize:v})}><option>14px</option><option>15px</option><option>16px</option><option>17px</option><option>18px</option></Select></Field><label className="flex items-center gap-3 text-sm font-semibold pt-7"><input type="checkbox" checked={themeForm.accessibility.underlineLinks} onChange={e=>updateNested('accessibility',{underlineLinks:e.target.checked})}/> Sublinhado em links</label><label className="flex items-center gap-3 text-sm font-semibold pt-7"><input type="checkbox" checked={themeForm.accessibility.strongFocus} onChange={e=>updateNested('accessibility',{strongFocus:e.target.checked})}/> Foco de teclado forte</label></div><div className="grid md:grid-cols-2 gap-4"><Audit title="Texto sobre fundo" ratio={calculateContrastRatio(colors.textPrimary,colors.bg)} status={textBg.label}/><Audit title="Texto sobre superfície" ratio={calculateContrastRatio(colors.textPrimary,colors.surface)} status={textSurface.label}/></div></section>
    <section className="theme-card p-5 space-y-5"><h3 className="font-bold flex items-center gap-2"><MousePointer2 className="w-4 h-4"/>Movimento e voz</h3><div className="grid md:grid-cols-2 gap-4"><Field label="Duração das animações"><Select value={themeForm.motion.duration} onChange={v=>updateNested('motion',{duration:v})}><option>0ms</option><option>150ms</option><option>250ms</option><option>350ms</option><option>500ms</option></Select></Field><label className="flex items-center gap-3 text-sm font-semibold pt-7"><input type="checkbox" checked={themeForm.motion.reducedMotion} onChange={e=>updateNested('motion',{reducedMotion:e.target.checked})}/> Respeitar preferência de movimento reduzido</label><Field label="CTA de projeto"><Text value={themeForm.uxVoice.ctaProject} onChange={v=>updateNested('uxVoice',{ctaProject:v})}/></Field></div></section>
  </form>;
};
function Audit({title,ratio,status}:{title:string;ratio:number;status:string}){return <div className="p-4 rounded-xl border flex items-center justify-between" style={{borderColor:'var(--theme-border)'}}><div><strong className="text-sm">{title}</strong><div className="text-xs mt-1" style={{color:'var(--theme-text-secondary)'}}>{ratio.toFixed(2)}:1</div></div><span className="text-xs font-bold px-2.5 py-1 rounded-lg" style={{backgroundColor:ratio>=4.5?'#DCFCE7':'#FEE2E2',color:ratio>=4.5?'#166534':'#991B1B'}}>{status}</span></div>}
